# [1교시] - 주요 데이터 구조

pandas series 구조 이해

In [ ]:
# openpyxl : excel 파일 처리용
%pip install pandas numpy openpyxl

# pandas 주요 데이터 구조
series: 1차원 데이터 구조 (배열 + 인덱스)
- 인덱스는 문자도 들어갈 수 있다.


dataframe: 2차원 데이터 구조 (표 형태)

In [ ]:
import pandas as pd

In [ ]:
s = pd.Series(range(100, 105), index=['a', 'b', 'c', 'd', 'e'])

s

In [ ]:
s = pd.Series(range(10))

s

In [ ]:
data = {'서울': 9720846, '부산': 3404423, '인천': 2947217}
s = pd.Series(data)

s

In [ ]:
# 인덱스의 중복이 허용이 된다.
s = pd.Series(range(100, 105), index=['a', 'b', 'a', 'd', 'e'])
s

In [ ]:
# 지금은 괜찮지만 나중에 명령어가 바뀔 수 있다.
s[0]
# s.iloc[0]

In [ ]:
s[:2]

In [ ]:
s.shape

In [ ]:
# 인덱스를 지정하면 값이 반복됨
# s = pd.Series(100, index = ['a', 'b', 'c'])
s

In [ ]:
s = pd.Series(range(100,105))
s

In [ ]:
# 인덱스 a가 없기 때문에 에러
s['a']

In [ ]:
s = pd.Series(range(100, 105), index=['a', 'b', 'c', 'd', 'e'])
s['a':'c']

In [ ]:
#팬시 인덱싱과 비슷한 기능을 가짐
s[['a', 'c']]

In [ ]:
# 불린형도 가능
s[[True, True, False, False, False]]

In [ ]:
s > 101

In [ ]:
# 값의 개수
data = {'서울': 9720846, '부산': 3404423, '인천': 2947217}
s = pd.Series(data)
s.value_counts()

In [ ]:
data = {'업직종 대분류': '음식점, 소매점, 음식점', '업직종 소분류': ['분식점', '슈퍼', '한식당']}
s = pd.Series(data)
s

In [ ]:
data = ['음식점', '소매점', '음식점', '음식점', '소매점', '음식점', '음식점', '소매점', '음식점']
s = pd.Series(data)
s.value_counts()
s.index

In [ ]:
# 값의 개수
data = {'서울': 9720846, '부산': 3404423, '인천': 2947217}
s = pd.Series(data)
s.index

In [ ]:
# 랜덤 값을 뽑을 때 seed값을 고정하는게 중요
import numpy as np
np.random.seed(42)
data = np.random.randint(10, 100, 50)
s = pd.Series(data)
s

# [2교시]

In [ ]:
# 평균값과 중위치값의 값의 크기가 차이많이 날 때 이상치라고 함
import numpy as np
np.random.seed(42)
data = np.random.randint(10,100,50)
s = pd.Series(data)
s.describe()['50%']

In [ ]:
s.describe().index

In [ ]:
s1 = pd.Series([1, 2, 3], index=['a', 'b', 'c'])
s2 = pd.Series([10, 20, 30], index=['a', 'b', 'cc'])

# index가 일치하는 요소끼리 연산
s1 + s2

# 요소가 같지 않을 경우, NaN(결측치)로 반환

In [ ]:
# 결측치 확인
s = s1 + s2
# 결측치면 True
s.isna()
# 결측치가 아니면 True
s.notnull()

In [ ]:
s = s1 + s2
# s에서 결측치를 찾아라
# s값에 []를 씌워라
s[s.isna()].index

In [ ]:
s1 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
s2 = pd.Series([10, 20, 30, 40], index=['a', 'bb', 'c', 'dd'])

# index가 일치하는 요소끼리 연산
s1 + s2

# 요소가 같지 않을 경우, NaN(결측치)로 반환

In [ ]:
import pandas as pd
s1 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
s2 = pd.Series([10, 20, 30, 40], index=['a', 'bb', 'c', 'dd'])
s = s1 + s2
# 결측치를 제거
# s.dropna()
s.fillna(s.mean())

In [ ]:
# descending은 없기 때문에 ascending=false를 이용해야 한다 
s.sort_values(ascending=False)
s.sort_index()

In [ ]:
### 예제 1: 학생 성적 관리
# - 5명의 학생 성적을 Series로 생성
# - 평균, 최고점, 최저점 계산
# - 80점 이상 학생 필터링

In [ ]:
data = {
    '홍길동' : 95,
    '이순신' : 75,
    '강감찬' : 94,
    '철수' : 77,
    '철이' : 90,
}               
s = pd.Series(data)
s

In [ ]:
s.mean()

In [ ]:
s.min()

In [ ]:
s.max()

In [ ]:
pd.Series(['s.mean()', 's.min()', 's.max()'], index=['평균', '최소값', '최대값'])

s[s>=80]

In [ ]:
### 예제 2: 도시별 인구 데이터
# - 주요 도시의 인구를 딕셔너리로 Series 생성
# - 인구 순으로 정렬
# - 특정 인구 범위 필터링

In [ ]:
population = pd.Series({
    '인천': 2947217,
    '서울': 9720846,
    '부산': 3404423,
    '대구': 2427954,
    '대전': 1471040
})

# 인구순으로 정렬(오름차순)
population.sort_values(ascending=False)
# 특정 인구 범위 필터링
population[population >= 2500000]

In [ ]:
### 예제 3: 결측치가 있는 데이터
# - 결측치를 포함한 Series 생성
# - 결측치 확인 및 처리
# - 통계량 계산

In [ ]:
np.random.seed(42)
data = np.random.randn(20)
data

In [ ]:
index = np.random.randint(0, 20, 5)
data[index] = np.nan
data

In [ ]:
# 결측치 확인 및 처리
# 결측치가 아닌 데이터만 추출, 결측치를 평균이나 최대 또는 최소 또는 중위수로 채우기
# 통계량 계산 - 기술 통계[최대, 최소, 평균, 4분위소]

In [ ]:
s = pd.Series(data)
s

In [ ]:
# 기술 통계
s.describe()

In [ ]:
# 결측치 확인
s.isna()

In [ ]:
# 결측치만
s[s.isna()]

In [ ]:
# 결측치가 아닌 것들
s[~s.isna()]

# [3교시]

DataFrame

In [ ]:
# key value 형태

data = {
    'name': ['Kim', 'Lee', 'Park'],
    'age': [25, 30, 35],
    'city': ['Seoul', 'Busan', 'Incheon']
}
df = pd.DataFrame(data)
df

In [ ]:
# 리스트의 딕셔너리 형태
data = [
    {'name': 'Kim', 'age': 25, 'city': 'Seoul'},
    {'name': 'Lee', 'age': 30, 'city': 'Busan'},
    {'name': 'Park', 'age': 35, 'city': 'Incheon'}
]
df = pd.DataFrame(data)
df

In [ ]:
# 2차원 리스트로 생성
data = {
    'name': ['Kim', 'Lee', 'Park'],
    'age': [25, 30, 35],
    'city': ['Seoul', 'Busan', 'Incheon']
}
df = pd.DataFrame(data,
                # columns=['name', 'age', 'city']
                )
df

In [ ]:
# Series로 생성
s1 = pd.Series(['Kim', 'Lee', 'Park'], name='name')
s2 = pd.Series([25, 30, 35], name='age')
df = pd.DataFrame({'name': s1, 'age': s2})
df

In [ ]:
# 시리즈별 인덱스 정보가 다를 때 경우의 수로 df생성
s1 = pd.Series(['Kim', 'Lee', 'Park'], name='name')
s2 = pd.Series([25, 30, 35], index=['a', 'b', 'c'])
df = pd.DataFrame({'name': s1, 'age': s2})
df

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
df = pd.DataFrame(arr, columns=['A', 'B', 'C'])
a = pd.Series([1, 2, 3])
b = pd.Series([4, 5, 6])
c = pd.Series([7, 8, 9])
pd.dataframe=(a, b, c)

In [ ]:
import pandas as pd

In [ ]:
data = {
    'city' : ['서울', '대전', '대구', '부산'],
    'data1' : np.random.randint(100000, 1000000, 4),
    'data2' : np.random.randn(4),
}
df = pd.DataFrame(data)
df

In [ ]:
print(df.shape)
print(df.size)
print(df.ndim)
print(list(df.index)) 
print(df.columns)
print(df.values)
print(df.dtypes) # 문자, 정수, 실수가 섞여있기 때문에 object

In [ ]:
# 전체 정보 (타입, 결측치 등)
# ojbect: 문자 / int: 정수 / float: 실수
df.info()

In [ ]:
# 수치형 데이터만 정리
df.describe()

In [ ]:
# unique 고유값
df.describe(include='all')

# 수치형 데이터에는 중복의 개념이 없기 때문에, unique top freq 값이 NaN이다.
# freq 빈도수(얼마나 나왔는지)
# mean : NaN (city는 평균의 의미가 없다)

                 연도   동명          부과건수          견인건수       단속원금(원)     데이터기준일자
count     66.000000   66     66.000000     66.000000  6.600000e+01          66
unique          NaN   16           NaN           NaN           NaN           1
top             NaN  개포동           NaN           NaN           NaN  2022-02-07
freq            NaN    5           NaN           NaN           NaN          66
mean    2019.000000  NaN  20413.969697   1277.848485  8.566118e+08         NaN
std        1.414214  NaN  20107.746106   2221.939072  8.214809e+08         NaN
min     2017.000000  NaN   1071.000000      2.000000  5.150000e+07         NaN
25%     2018.000000  NaN   5851.000000    191.750000  2.651138e+08         NaN
50%     2019.000000  NaN  10217.000000    435.500000  4.109800e+08         NaN
75%     2020.000000  NaN  29005.000000   1201.000000  1.304418e+09         NaN
max     2021.000000  NaN  90385.000000  12394.000000  3.615400e+09         NaN

In [ ]:
# 각 속성별 호출 방법
df.describe(include='object')
df.describe(include='int32')
df.describe(include='float64')

In [ ]:
data = {
    'city' : ['서울','대전','대구','부산'],
    'data1' : np.random.randint(100000,1000000,4),
    'data2' : np.random.randn(4),
}
df = pd.DataFrame(data)
df

In [ ]:
df.city

In [ ]:
df[['city']]

In [ ]:
df[['city', 'data1']]

In [ ]:
# BroadCasting의 예시
df['salary'] = [3000, 4000, 5000, 6000]
df['salary2'] = 0
df2 = df.copy()
df2

In [ ]:
df2.drop('salary2', axis=1)
df

In [ ]:
# index = 0 삭제
# axis=1일때는 해당 컬럼명을 찾는다.
df.drop(0, axis=0)

In [ ]:
# 원본까지 삭제 할 때
df2.drop('salary2', axis=1, inplace=True)
df2

In [ ]:
df2.columns = ['city', 'data10', 'data20', 'salary', 'salary2']
df2

# [4교시]

In [ ]:
# pwd : 현재 파일의 경로 확인
filepath = '20250731.csv'
df = pd.read_csv(filepath)
df.head()

In [ ]:
# 결측치 개수
for i in df:
    df[i]
# 기술 통계(숫자 컬럼만) 기술 통계(문자들만)

# info() 사용해보기

# 등록년도 컬럼 삭제하기

# 소속 시장명(또는 상점가)의 컬럼명을 시장명-상점가 로 변경

# 소재지 그리고 취급품목들 등록년도의 각각의 개수

# 소재지 그리고 취급품목들 등록년도의 각각의 종류들
print(df['소재지'].unique())
# 지류형 가맹 여부가 N인 데이터로 이루어진 데이터프레임 즉 데이터 출력

# 등록년도 컬럼 삭제하기

# 등록년도 컬럼 삭제해서 원본을 변경하기

In [ ]:
#  df의 모든 정보 확인
df.describe(include='all')

In [ ]:
s = pd.read_csv(filepath)
s

In [ ]:
# 결측치 개수
for colname in df:
    print(colname, df[df[colname].isna()].shape[0])

In [ ]:
# 기술 통계(숫자 컬럼만) 기술 통계(문자들만)
# df.describe()
df.describe(include='object')

In [ ]:
print(df['소재지'].unique())

In [ ]:
df[df['지류형 가맹 여부'] == 'N']

In [ ]:
df.drop('등록년도', axis=1)

In [ ]:
df.drop('등록년도', axis=1, inplace=True)

# [5교시]

In [ ]:
## loc는 location의; 약자
## iloc는 index location

## 위치 기반 인덱싱은 주로 숫자열로 이루어짐

## 레이블 기반 인덱싱은 주로 문자열로 이루어짐

In [ ]:
import pandas as pd

filepath = '20250731.csv'
df = pd.read_csv(filepath)
df2 = df.head().copy()
df2

In [ ]:

df3 = df2.set_index('소재지').copy()
df3

In [ ]:

# df3.loc['광주','가맹점명':'취급품목']
df3.iloc[[1,2,4], 0:3]

In [ ]:
## 행을 추가 할 때
# concat 합칠 때 사용하는 함수

In [ ]:
sample_df1 = df.iloc[:5,:2]
sample_df2 = df.iloc[:5,-2:]

In [ ]:
sample_df1

In [ ]:
sample_df2

In [ ]:
#axis=0 : 위아래로 합치기, axis=1 : 옆으로 합치기
pd.concat([sample_df1, sample_df2], axis=0)
sample_df3 = pd.concat([sample_df1, sample_df2], axis=1)

In [ ]:
sample_df3.info()

In [ ]:
sample_df3.reset_index()

In [ ]:
sample_df4 = sample_df3.reset_index()
sample_df4.rename(columns={'index':'data'}, inplace = True)
sample_df4.set_index('data').reset_index()

In [ ]:
sample_df4 = sample_df3.reset_index()
sample_df4.rename(columns={'index':'data'}, inplace = True)
sample_df4.set_index('가맹점명').reset_index()

In [ ]:
sample_df3.reset_index()
sample_df3.reset_index(drop=True)

In [5]:
import pandas as pd
filepath = '20250731.csv'
df = pd.read_csv(filepath)
df.head()

,가맹점명,소속 시장명(또는 상점가),소재지,취급품목,지류형 가맹 여부,디지털형 가맹 여부,등록년도
0,초마맨1981,권율 골목형상점가,경기,짜장면 짬뽕 탕수육,Y,Y,2025
1,못난이 꽈배기,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,꽈배기 도너츠,Y,Y,2025
2,일곡열쇠철물,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,열쇠,Y,Y,2025
3,참새 방앗간,권율 골목형상점가,경기,육전 새우전,Y,Y,2025
4,뿔라헤어컷,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,미용,Y,Y,2025

In [6]:
df.drop([0,1])

,가맹점명,소속 시장명(또는 상점가),소재지,취급품목,지류형 가맹 여부,디지털형 가맹 여부,등록년도
2,일곡열쇠철물,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,열쇠,Y,Y,2025
3,참새 방앗간,권율 골목형상점가,경기,육전 새우전,Y,Y,2025
4,뿔라헤어컷,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,미용,Y,Y,2025
5,자인명,권율 골목형상점가,경기,음료,Y,Y,2025
6,농민야채청과,권선종합시장,경기,채소 등,Y,Y,2025
...,...,...,...,...,...,...,...
150536,태성마트,단양구경시장(단양인정시장),충북,식잡,Y,Y,2010
150537,동산닭집,단양구경시장(단양인정시장),충북,"일반한식,생닭",Y,Y,2010
150538,파마미용실,단양구경시장(단양인정시장),충북,일반미용업,Y,Y,2010
150539,두메하누,단양구경시장(단양인정시장),충북,한식점업,Y,Y,2010
150540,단양보리밥,단양구경시장(단양인정시장),충북,분식,Y,Y,2010

In [ ]:
df.drop('가맹점명', axis=1)

In [11]:
df['등록년도'].unique()

array([2025, 2021, 2010, 2024, 2022, 2023, 2011, 2020, 2013, 2019, 2018,
       2017, 2016, 2015, 2014, 2012])

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150541 entries, 0 to 150540
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   가맹점명            150501 non-null  object
 1   소속 시장명(또는 상점가)  150541 non-null  object
 2   소재지             150541 non-null  object
 3   취급품목            150248 non-null  object
 4   지류형 가맹 여부       150541 non-null  object
 5   디지털형 가맹 여부      150541 non-null  object
 6   등록년도            150541 non-null  int64
dtypes: int64(1), object(6)
memory usage: 8.0+ MB

In [13]:
# 2020년 이후 데이터만 추출
df[df['등록년도'] >= 2020]

,가맹점명,소속 시장명(또는 상점가),소재지,취급품목,지류형 가맹 여부,디지털형 가맹 여부,등록년도
0,초마맨1981,권율 골목형상점가,경기,짜장면 짬뽕 탕수육,Y,Y,2025
1,못난이 꽈배기,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,꽈배기 도너츠,Y,Y,2025
2,일곡열쇠철물,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,열쇠,Y,Y,2025
3,참새 방앗간,권율 골목형상점가,경기,육전 새우전,Y,Y,2025
4,뿔라헤어컷,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,미용,Y,Y,2025
...,...,...,...,...,...,...,...
124792,(주)현대걸리버투어,군포당동로시장상점가,경기,"써비스(국내외여행알선업) 도매업(플라스틱류,기타무",Y,Y,2022
132954,농협쌀판매장,구리전통시장,경기,"도소매업(수산물도매업,기타산업용농산물",Y,Y,2021
137507,유피,구리구도심상권활성화,경기,도매및소매업(셔츠및블라우스소매업)소매업(전자상거래),Y,Y,2021
148657,영 스토어,관고전통시장,경기,"도매및소매업(일용잡화,식자재유통,의약외품,통신",Y,Y,2021
150187,무자식당,가조상점가,경남,한식,Y,Y,2024

In [15]:
# 2020년 이후 데이터만 추출
df[df['등록년도'].isin([2020, 2025])]

,가맹점명,소속 시장명(또는 상점가),소재지,취급품목,지류형 가맹 여부,디지털형 가맹 여부,등록년도
0,초마맨1981,권율 골목형상점가,경기,짜장면 짬뽕 탕수육,Y,Y,2025
1,못난이 꽈배기,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,꽈배기 도너츠,Y,Y,2025
2,일곡열쇠철물,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,열쇠,Y,Y,2025
3,참새 방앗간,권율 골목형상점가,경기,육전 새우전,Y,Y,2025
4,뿔라헤어컷,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,미용,Y,Y,2025
...,...,...,...,...,...,...,...
96090,주식회사 하원,누웨마루거리상점가,제주,액세서리,Y,Y,2020
96091,네이처컬렉션,누웨마루거리상점가,제주,화장품,Y,Y,2020
96092,의정,누웨마루거리상점가,제주,한식,Y,Y,2020
96093,GS25연동중앙점,누웨마루거리상점가,제주,생필품,Y,Y,2020
96094,마코스포츠,서귀포중심상가,제주,의류및신발,Y,Y,2020

# [6교시]
## 20220207.csv 실습

In [1]:
import pandas as pd
filepath = '20220207.csv'
df = pd.read_csv(filepath, encoding='cp949')
df.head()

     연도   동명   부과건수  견인건수     단속원금(원)     데이터기준일자
0  2017  개포동   9409   284   376360000  2022-02-07
1  2017  논현동  71771  2054  2870840000  2022-02-07
2  2017  대치동  55222  2624  2208880000  2022-02-07
3  2017  도곡동  10763   130   430520000  2022-02-07
4  2017  삼성동  36472  1507  1458880000  2022-02-07

In [2]:
# 결측치 여부 확인, 만약 있다면 결측치가 있는 데이터만 출력
# 결측치를 채우기(평균 또는 중위수, 문자열은 빈도수가 많은 문자열로 대처)
# 단속원금이 가장 큰 순으로 정렬해서 top 5 출력
# 데이터 기준일자는 언제부터 언제까지인지

In [3]:
df.info()
#결측치 여부는 확인 안됨!

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66 entries, 0 to 65
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   연도       66 non-null     int64
 1   동명       66 non-null     object
 2   부과건수     66 non-null     int64
 3   견인건수     66 non-null     int64
 4   단속원금(원)  66 non-null     int64
 5   데이터기준일자  66 non-null     object
dtypes: int64(4), object(2)
memory usage: 3.2+ KB

In [5]:
df.isna().any()
#any는 한 개라도 true가 있으면 true

연도         False
동명         False
부과건수       False
견인건수       False
단속원금(원)    False
데이터기준일자    False
dtype: bool

In [8]:
df.rename(columns={'단속원금(원)':'단속원금'}, inplace=True)
df['단속원금']
df.sort_values(by=['단속원금'],ascending=False)

      연도   동명   부과건수   견인건수        단속원금     데이터기준일자
9   2017  역삼동  90385   4214  3615400000  2022-02-07
1   2017  논현동  71771   2054  2870840000  2022-02-07
35  2019  역삼동  68450  12394  2759485000  2022-02-07
22  2018  역삼동  67609   3720  2704360000  2022-02-07
41  2020  논현동  27407   1165  2229425000  2022-02-07
..   ...  ...    ...    ...         ...         ...
24  2018  자곡동   2669    104   106760000  2022-02-07
45  2020  세곡동   2598      4   106340000  2022-02-07
64  2021  자곡동   1967      3    95680000  2022-02-07
51  2020  자곡동   1071      8    52500000  2022-02-07
36  2019  율현동   1268    115    51500000  2022-02-07

[66 rows x 6 columns]

In [10]:
# top 5
df_5 = df.sort_values(by=['단속원금'],ascending=False).iloc[:5]
df_5

      연도   동명   부과건수   견인건수        단속원금     데이터기준일자
9   2017  역삼동  90385   4214  3615400000  2022-02-07
1   2017  논현동  71771   2054  2870840000  2022-02-07
35  2019  역삼동  68450  12394  2759485000  2022-02-07
22  2018  역삼동  67609   3720  2704360000  2022-02-07
41  2020  논현동  27407   1165  2229425000  2022-02-07

In [12]:
# 연도를 확인하고 싶을 때
df['연도']
df['연도'].min(), df['연도'].max()

(2017, 2021)

# 세션 3 : 데이터 로드 및 저장

## 1. 데이터 입출력 개요

In [ ]:
import pandas as pd                         #header=None : 헤더가 없음
pd.read_csv('20220207.csv', encoding='cp949', header=None)

In [26]:
import pandas as pd                         
df = pd.read_csv('20220207.csv', encoding='cp949', header=0)
df_2017 = df[df['연도'] == 2017]
df_2017.to_csv('2017.csv',encoding='utf-8')

In [30]:
df_2017.to_excel('2017_excel.xlsx')

In [33]:
df_2017.to_json('2017_json.json', force_ascii=False, orient='records')

In [ ]:
# 파일 DB
# import sqlite3

In [ ]:
%pip install sqlalchemy

In [16]:
import os
import pandas as pd
from dotenv import load_dotenv
load_dotenv()

user_id = os.getenv('DB_USER')
user_pwd = os.getenv('DB_PASSWORD')
db_name = os.getenv('DB_NAME')

from sqlalchemy import create_engine, text
engine = create_engine(f'mysql+pymysql://{user_id}:{user_pwd}@localhost:3306/{db_name}')
conn = engine.connect()
result = conn.execute(text("select 1"))
print(result.fetchall())
conn.close()

python-dotenv could not parse statement starting at line 7

[(1,)]

In [17]:
engine = create_engine(f'mysql+pymysql://{user_id}:{user_pwd}@localhost:3306/{db_name}')
pd.read_sql('select * from code_use_fuel', engine)

   code           name
0     1            CNG
1    10        휘발유(유연)
2    11           기타연료
3     2             경유
4     3             수소
5     4            엘피지
6     5             전기
7     6  하이브리드(CNG+전기)
8     7  하이브리드(휘발유+전기)
9     8            휘발유
10    9        휘발유(무연)

# [7교시]

In [ ]:
import pandas as pd
from glob import glob

filepath = 'data/*.csv'
files = glob(filepath)
print(files[8])
df = pd.read_csv(files[8],encoding='utf-8')
df.head()

In [48]:
# 특정한 컬럼을 삭제 할 때, ('컬럼명', axis=1)
df2 = df.drop('상가업소번호', axis=1)
df2.columns
# 컬럼 중에 '코드'만 들어있는 컬럼들을 추출

Index(['상호명', '지점명', '상권업종대분류코드', '상권업종대분류명', '상권업종중분류코드', '상권업종중분류명',
       '상권업종소분류코드', '상권업종소분류명', '표준산업분류코드', '표준산업분류명', '시도코드', '시도명', '시군구코드',
       '시군구명', '행정동코드', '행정동명', '법정동코드', '법정동명', '지번코드', '대지구분코드', '대지구분명',
       '지번본번지', '지번부번지', '지번주소', '도로명코드', '도로명', '건물본번지', '건물부번지', '건물관리번호',
       '건물명', '도로명주소', '구우편번호', '신우편번호', '동정보', '층정보', '호정보', '경도', '위도'],
      dtype='object')

In [56]:
result = []
for cname in df2.columns:
    if '코드' in cname:
        result.append(cname)

result

['상권업종대분류코드',
 '상권업종중분류코드',
 '상권업종소분류코드',
 '표준산업분류코드',
 '시도코드',
 '시군구코드',
 '행정동코드',
 '법정동코드',
 '지번코드',
 '대지구분코드',
 '도로명코드']

In [58]:
[cname for cname in df2.columns if '코드' in cname]

['상권업종대분류코드',
 '상권업종중분류코드',
 '상권업종소분류코드',
 '표준산업분류코드',
 '시도코드',
 '시군구코드',
 '행정동코드',
 '법정동코드',
 '지번코드',
 '대지구분코드',
 '도로명코드']

In [66]:
result = [cname for cname in df2.columns if '코드' in cname] + ['지번본번지', '지번부번지', '지번주소', '건물관리번호']
result += ['도로명', '건물본번지', '건물부번지', '건물명', '구우편번호', '신우편번호', '동정보', '층정보', '호정보']
df3 = df2.drop(result, axis=1)
df3.head()

,상호명,지점명,상권업종대분류명,상권업종중분류명,상권업종소분류명,표준산업분류명,시도명,시군구명,행정동명,법정동명,대지구분명,도로명주소,경도,위도
0,60계치킨암사,선사점,음식,기타 간이,치킨,치킨 전문점,서울특별시,강동구,암사2동,암사동,대지,서울특별시 강동구 상암로3길 8,127.126859,37.550810
1,성심인력공사,NaN,시설관리·임대,고용 알선,고용 알선업,고용 알선업,서울특별시,용산구,남영동,동자동,대지,서울특별시 용산구 한강대로 385,126.972240,37.552803
2,칸토빈,NaN,음식,비알코올,카페,커피 전문점,서울특별시,강서구,공항동,공항동,산,서울특별시 강서구 방화동로 30,126.810493,37.563548
3,까치노래연습장,NaN,예술·스포츠,유원지·오락,노래방,노래 연습장 운영업,서울특별시,노원구,상계5동,상계동,대지,서울특별시 노원구 한글비석로23길 2,127.071218,37.660715
4,금빛주얼리,NaN,소매,시계·귀금속 소매,시계/귀금속 소매업,시계 및 귀금속 소매업,서울특별시,종로구,종로1.2.3.4가동,묘동,대지,서울특별시 종로구 돈화문로10길 2,126.991861,37.572331

In [69]:
df3['상권업종소분류명'].value_counts()

상권업종소분류명
백반/한정식           26376
부동산 중개/대리업       25059
카페               21624
경영 컨설팅업          20952
미용실              19913
                 ...
기타 회계 관련 서비스업       30
낚시터 운영업             26
얼음 소매업              23
비디오방                23
캠핑/글램핑              16
Name: count, Length: 247, dtype: int64

In [ ]:
#상권업종소분류명이 어떤 기준으로 등록이 되어있는지
df3[df3['상권업종소분류명'] == '비디오방']

In [72]:
# 문자열 메서드를 이용해서 DVD에 속하는 업종들 찾아보기
df3['상호명'].str.contains('DVD').sum()

np.int64(11)

In [ ]:
df3[df3['상호명'].str.contains('치킨')]

In [ ]:
# 특정 컬럼에 결측치가 하나라도 있을 경우
df3[df3.isna().any(axis=1)]

In [88]:
df3[df3.isna().any(axis=1)]

,상호명,지점명,상권업종대분류명,상권업종중분류명,상권업종소분류명,표준산업분류명,시도명,시군구명,행정동명,법정동명,대지구분명,도로명주소,경도,위도
1,성심인력공사,NaN,시설관리·임대,고용 알선,고용 알선업,고용 알선업,서울특별시,용산구,남영동,동자동,대지,서울특별시 용산구 한강대로 385,126.972240,37.552803
2,칸토빈,NaN,음식,비알코올,카페,커피 전문점,서울특별시,강서구,공항동,공항동,산,서울특별시 강서구 방화동로 30,126.810493,37.563548
3,까치노래연습장,NaN,예술·스포츠,유원지·오락,노래방,노래 연습장 운영업,서울특별시,노원구,상계5동,상계동,대지,서울특별시 노원구 한글비석로23길 2,127.071218,37.660715
4,금빛주얼리,NaN,소매,시계·귀금속 소매,시계/귀금속 소매업,시계 및 귀금속 소매업,서울특별시,종로구,종로1.2.3.4가동,묘동,대지,서울특별시 종로구 돈화문로10길 2,126.991861,37.572331
5,골든공인중개사사무소,NaN,부동산,부동산 서비스,부동산 중개/대리업,부동산 중개 및 대리업,서울특별시,마포구,성산2동,성산동,대지,서울특별시 마포구 월드컵로34길 6,126.903067,37.564570
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
534971,오부찌,NaN,음식,한식,백반/한정식,한식 일반 음식점업,서울특별시,송파구,문정2동,문정동,대지,서울특별시 송파구 송파대로 167,127.120755,37.484557
534972,생각과생각사이,NaN,음식,한식,백반/한정식,한식 일반 음식점업,서울특별시,용산구,용산2가동,용산동2가,대지,서울특별시 용산구 신흥로 11,126.986332,37.539624
534973,살림,NaN,소매,기타 상품 소매,그 외 기타 상품 전문 소매업,그 외 기타 분류 안된 상품 전문 소매업,서울특별시,송파구,잠실2동,잠실동,대지,서울특별시 송파구 올림픽로 119,127.084186,37.512087
534975,하루곰탕,NaN,음식,한식,국/탕/찌개류,한식 일반 음식점업,서울특별시,동대문구,장안2동,장안동,대지,서울특별시 동대문구 사가정로25길 21,127.070371,37.579807
534977,에이치아이디자인,NaN,소매,장식품 소매,기념품점,기념품; 관광 민예품 및 장식용품 소매업,서울특별시,중구,광희동,오장동,대지,서울특별시 중구 동호로33길 24,127.000860,37.565655

# [8교시]

In [92]:
# df3.drop('지점명', axis=1)
df4 = df3.drop(columns=['지점명'])
df4.head(1)

,상호명,상권업종대분류명,상권업종중분류명,상권업종소분류명,표준산업분류명,시도명,시군구명,행정동명,법정동명,대지구분명,도로명주소,경도,위도
0,60계치킨암사,음식,기타 간이,치킨,치킨 전문점,서울특별시,강동구,암사2동,암사동,대지,서울특별시 강동구 상암로3길 8,127.126859,37.55081

In [104]:
df4.query('상권업종소분류명 == "치킨"')

# df4[df4['상권업종소분류명'] == '치킨'] 둘 중 편한걸로 사용하면 된다

,상호명,상권업종대분류명,상권업종중분류명,상권업종소분류명,표준산업분류명,시도명,시군구명,행정동명,법정동명,대지구분명,도로명주소,경도,위도
0,60계치킨암사,음식,기타 간이,치킨,치킨 전문점,서울특별시,강동구,암사2동,암사동,대지,서울특별시 강동구 상암로3길 8,127.126859,37.550810
72,인생닭강정,음식,기타 간이,치킨,간이 음식 포장 판매 전문점,서울특별시,중랑구,망우본동,망우동,대지,서울특별시 중랑구 망우로62길 20,127.097498,37.598194
123,큰집닭강정,음식,기타 간이,치킨,치킨 전문점,서울특별시,동대문구,신설동,용두동,대지,서울특별시 동대문구 천호대로13길 16,127.030078,37.574688
405,비에이치씨제기역점,음식,기타 간이,치킨,치킨 전문점,서울특별시,동대문구,용두동,용두동,대지,서울특별시 동대문구 왕산로26길 23,127.036554,37.577020
435,굽네치킨마포도화점,음식,기타 간이,치킨,치킨 전문점,서울특별시,마포구,도화동,도화동,대지,서울특별시 마포구 도화4길 23,126.951164,37.540885
...,...,...,...,...,...,...,...,...,...,...,...,...,...
534805,황금통닭,음식,기타 간이,치킨,한식 일반 음식점업,서울특별시,중구,신당5동,신당동,대지,서울특별시 중구 퇴계로 426,127.018902,37.565464
534814,1번지통닭,음식,기타 간이,치킨,한식 일반 음식점업,서울특별시,성북구,종암동,종암동,대지,서울특별시 성북구 종암로24가길 16,127.035852,37.600743
534869,지코바문정,음식,기타 간이,치킨,한식 일반 음식점업,서울특별시,송파구,장지동,문정동,대지,서울특별시 송파구 새말로 171,127.131770,37.485798
534871,처갓집양념치킨북,음식,기타 간이,치킨,한식 일반 음식점업,서울특별시,서대문구,충현동,충정로3가,대지,서울특별시 서대문구 경기대로9길 81,126.959705,37.564423
534931,60계치킨서울우,음식,기타 간이,치킨,한식 일반 음식점업,서울특별시,양천구,신월5동,신월동,대지,서울특별시 양천구 화곡로13길 13,126.833453,37.540553

In [121]:
# df4[df4['상권업종소분류명'] == '치킨']['상권업종소분류명'] = '통닭'
df4.loc[df4['상권업종소분류명'] == '치킨' ,'상권업종소분류명'] = '통닭'

In [125]:
(df4['상권업종소분류명']=='통닭').sum()

np.int64(5167)

In [128]:
df4.loc[df4['상권업종소분류명']=='통닭', ['상호명', '상권업종대분류명']] = ['통닭집', 'chicken']

In [129]:
df4[df4['상권업종소분류명']=='통닭']

,상호명,상권업종대분류명,상권업종중분류명,상권업종소분류명,표준산업분류명,시도명,시군구명,행정동명,법정동명,대지구분명,도로명주소,경도,위도
0,통닭집,chicken,기타 간이,통닭,치킨 전문점,서울특별시,강동구,암사2동,암사동,대지,서울특별시 강동구 상암로3길 8,127.126859,37.550810
72,통닭집,chicken,기타 간이,통닭,간이 음식 포장 판매 전문점,서울특별시,중랑구,망우본동,망우동,대지,서울특별시 중랑구 망우로62길 20,127.097498,37.598194
123,통닭집,chicken,기타 간이,통닭,치킨 전문점,서울특별시,동대문구,신설동,용두동,대지,서울특별시 동대문구 천호대로13길 16,127.030078,37.574688
405,통닭집,chicken,기타 간이,통닭,치킨 전문점,서울특별시,동대문구,용두동,용두동,대지,서울특별시 동대문구 왕산로26길 23,127.036554,37.577020
435,통닭집,chicken,기타 간이,통닭,치킨 전문점,서울특별시,마포구,도화동,도화동,대지,서울특별시 마포구 도화4길 23,126.951164,37.540885
...,...,...,...,...,...,...,...,...,...,...,...,...,...
534805,통닭집,chicken,기타 간이,통닭,한식 일반 음식점업,서울특별시,중구,신당5동,신당동,대지,서울특별시 중구 퇴계로 426,127.018902,37.565464
534814,통닭집,chicken,기타 간이,통닭,한식 일반 음식점업,서울특별시,성북구,종암동,종암동,대지,서울특별시 성북구 종암로24가길 16,127.035852,37.600743
534869,통닭집,chicken,기타 간이,통닭,한식 일반 음식점업,서울특별시,송파구,장지동,문정동,대지,서울특별시 송파구 새말로 171,127.131770,37.485798
534871,통닭집,chicken,기타 간이,통닭,한식 일반 음식점업,서울특별시,서대문구,충현동,충정로3가,대지,서울특별시 서대문구 경기대로9길 81,126.959705,37.564423
534931,통닭집,chicken,기타 간이,통닭,한식 일반 음식점업,서울특별시,양천구,신월5동,신월동,대지,서울특별시 양천구 화곡로13길 13,126.833453,37.540553

In [ ]:
import numpy as np
import pandas as pd
data = {'age' : np.random.randint(1,100,50) }
df = pd.DataFrame(data)
df['lable'] = pd.qcut(df['age'], q=4, labels=['Q1', 'Q2', 'Q3', 'Q4'])
df

In [142]:
df = pd.DataFrame
pd.date_range('2026-01-01', periods=150, freq='D')

DatetimeIndex(['2026-01-01', '2026-01-02', '2026-01-03', '2026-01-04',
               '2026-01-05', '2026-01-06', '2026-01-07', '2026-01-08',
               '2026-01-09', '2026-01-10',
               ...
               '2026-05-21', '2026-05-22', '2026-05-23', '2026-05-24',
               '2026-05-25', '2026-05-26', '2026-05-27', '2026-05-28',
               '2026-05-29', '2026-05-30'],
              dtype='datetime64[ns]', length=150, freq='D')

In [149]:
import pandas as pd
from glob import glob
filepath = 'data/*.csv'
files = glob(filepath)
print(files[-1])
df = pd.read_csv(files[-1])
df.head()
df2 = df.copy()
# 결측치 확인 처리(삭제 또는 대처)
# 상호명에 '커피'가 포함된 데이터를 별도의 변수 df2에 저장하고
# 출력

data\소상공인시장진흥공단_상가(상권)정보_충북_202512.csv

In [152]:
# 특정 컬럼 삭제
df2.head()
df2.drop('상가업소번호', axis=1)

,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,표준산업분류명,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,루트커피,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,커피 전문점,...,4311311700105260000000001,굿샘빌딩,충청북도 청주시 흥덕구 2순환로 1254,361872,28378,NaN,1,NaN,127.430966,36.624251
1,강내염소탕,NaN,I2,음식,I201,한식,I20199,기타 한식 음식점,I56111,한식 일반 음식점업,...,4311310600107400000000055,NaN,충청북도 청주시 서원구 두꺼비로60번길 26-5,362160,28630,NaN,1,NaN,127.466194,36.609619
2,큰솔공인중개사사무소,NaN,L1,부동산,L102,부동산 서비스,L10203,부동산 중개/대리업,L68221,부동산 중개 및 대리업,...,4311112000103430000041479,NaN,충청북도 청주시 상당구 영운천로153번길 67,360803,28751,NaN,1,NaN,127.511229,36.624997
3,별이와콩이,NaN,G2,소매,G220,애완동물·용품 소매,G22001,애완동물/애완용품 소매업,G47852,애완용 동물 및 관련용품 소매업,...,4313010500111710000001563,NaN,충청북도 충주시 금릉로 104,380954,27357,NaN,NaN,NaN,127.927441,36.984312
4,영렘브란트미술학원,NaN,P1,교육,P106,기타 교육,P10611,미술학원,P85622,미술학원,...,4376025021107040008000001,NaN,충청북도 괴산군 괴산읍 읍내로 248,367805,28033,NaN,NaN,NaN,127.792851,36.805505
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90977,욤카페,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,커피 전문점,...,4313038526106860000000001,서충주신도시코아루더테라스,충청북도 충주시 중앙탑면 원앙9길 10,380922,27465,NaN,NaN,NaN,127.825325,37.017945
90978,유다이모니아팜,NaN,G2,소매,G205,식료품 소매,G20502,가축 사료 소매업,G47211,곡물; 곡분 및 가축 사료 소매업,...,4315011100101650044000001,NaN,충청북도 제천시 용두대로5길 28,390240,27187,NaN,NaN,NaN,128.195954,37.133210
90979,테크카랜드,NaN,G2,소매,G202,자동차 부품 소매,G20202,자동차 부품 소매업,G45219,기타 자동차 신품 부품 및 내장품 판매업,...,4313011800102510006000001,NaN,충청북도 충주시 금봉대로 740,380961,27330,NaN,NaN,NaN,127.936185,36.993948
90980,두피온,NaN,S2,수리·개인,S207,이용·미용,S20701,미용실,S96111,이용업,...,4315011100102130011000001,NaN,충청북도 제천시 용두대로5안길 19,390240,27187,NaN,NaN,NaN,128.195139,37.134326
90981,움버거앤윙스청주,가경점,I2,음식,I210,기타 간이,I21004,버거,I56192,피자; 햄버거; 샌드위치 및 유사 음식점업,...,4311311300106440005000001,NaN,충청북도 청주시 흥덕구 서현로 32,361260,28382,NaN,NaN,NaN,127.426599,36.617075

In [ ]:
# 특정 컬럼 삭제
df2.head()
df2.drop('상가업소번호', axis=1)

,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,표준산업분류명,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,루트커피,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,커피 전문점,...,4311311700105260000000001,굿샘빌딩,충청북도 청주시 흥덕구 2순환로 1254,361872,28378,NaN,1,NaN,127.430966,36.624251
1,강내염소탕,NaN,I2,음식,I201,한식,I20199,기타 한식 음식점,I56111,한식 일반 음식점업,...,4311310600107400000000055,NaN,충청북도 청주시 서원구 두꺼비로60번길 26-5,362160,28630,NaN,1,NaN,127.466194,36.609619
2,큰솔공인중개사사무소,NaN,L1,부동산,L102,부동산 서비스,L10203,부동산 중개/대리업,L68221,부동산 중개 및 대리업,...,4311112000103430000041479,NaN,충청북도 청주시 상당구 영운천로153번길 67,360803,28751,NaN,1,NaN,127.511229,36.624997
3,별이와콩이,NaN,G2,소매,G220,애완동물·용품 소매,G22001,애완동물/애완용품 소매업,G47852,애완용 동물 및 관련용품 소매업,...,4313010500111710000001563,NaN,충청북도 충주시 금릉로 104,380954,27357,NaN,NaN,NaN,127.927441,36.984312
4,영렘브란트미술학원,NaN,P1,교육,P106,기타 교육,P10611,미술학원,P85622,미술학원,...,4376025021107040008000001,NaN,충청북도 괴산군 괴산읍 읍내로 248,367805,28033,NaN,NaN,NaN,127.792851,36.805505
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90977,욤카페,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,커피 전문점,...,4313038526106860000000001,서충주신도시코아루더테라스,충청북도 충주시 중앙탑면 원앙9길 10,380922,27465,NaN,NaN,NaN,127.825325,37.017945
90978,유다이모니아팜,NaN,G2,소매,G205,식료품 소매,G20502,가축 사료 소매업,G47211,곡물; 곡분 및 가축 사료 소매업,...,4315011100101650044000001,NaN,충청북도 제천시 용두대로5길 28,390240,27187,NaN,NaN,NaN,128.195954,37.133210
90979,테크카랜드,NaN,G2,소매,G202,자동차 부품 소매,G20202,자동차 부품 소매업,G45219,기타 자동차 신품 부품 및 내장품 판매업,...,4313011800102510006000001,NaN,충청북도 충주시 금봉대로 740,380961,27330,NaN,NaN,NaN,127.936185,36.993948
90980,두피온,NaN,S2,수리·개인,S207,이용·미용,S20701,미용실,S96111,이용업,...,4315011100102130011000001,NaN,충청북도 제천시 용두대로5안길 19,390240,27187,NaN,NaN,NaN,128.195139,37.134326
90981,움버거앤윙스청주,가경점,I2,음식,I210,기타 간이,I21004,버거,I56192,피자; 햄버거; 샌드위치 및 유사 음식점업,...,4311311300106440005000001,NaN,충청북도 청주시 흥덕구 서현로 32,361260,28382,NaN,NaN,NaN,127.426599,36.617075